export type GeneratedThreeDAsset = {
  builtAt: string;
  webExport: string;
};

// AUTO-GENERATED by scripts/blender/build_assets.py. Do not hand-edit build state.
export const generatedThreeDAssets: Record<string, GeneratedThreeDAsset> = {
  "brand-neon-logo": { builtAt: "2026-09-21T14:52:28Z", webExport: "public/3d/brand/chill-bros-neon-logo.glb" },
  "rtu-training-shell": { builtAt: "2026-09-21T14:52:28Z", webExport: "public/3d/equipment/hvac/rtu-training-shell.glb" },
  "reach-in-refrigerator": { builtAt: "2026-09-21T14:52:28Z", webExport: "public/3d/equipment/refrigeration/reach-in-training.glb" },
  "ice-machine-training": { builtAt: "2026-09-21T14:52:28Z", webExport: "public/3d/equipment/ice/ice-machine-training.glb" },
  "commercial-fryer": { builtAt: "2026-09-21T14:52:28Z", webExport: "public/3d/equipment/cooking/commercial-fryer-training.glb" },
  "service-truck": { builtAt: "2026-09-21T14:52:28Z", webExport: "public/3d/vehicles/chill-bros-service-vehicle.glb" },
};
