"use client";

import { useMemo, useState, useTransition } from "react";
import { ChevronDown, Plus, Save, Search, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";

import { createPartAction, deletePartAction, updateFeeAction, updatePartAction } from "@/lib/chillbros/operations";
import type { FeeSetting, PartsCatalogItem } from "@/lib/chillbros/types";

const money = (value: number) => value.toLocaleString("en-US", { style: "currency", currency: "USD" });

export function InventoryAdmin({ parts, fees }: { parts: PartsCatalogItem[]; fees: FeeSetting[] }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [query, setQuery] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [newPart, setNewPart] = useState({ name: "", partNumber: "", defaultCost: "0", retailPrice: "0", stock: "0" });
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? parts.filter((p) => `${p.name} ${p.partNumber}`.toLowerCase().includes(q)) : parts; }, [parts, query]);
  const run = (fn: () => Promise<{ ok: boolean; error?: string }>, success: string) => { setError(null); setMessage(null); startTransition(async () => { const result = await fn(); if (!result.ok) { setError(result.error ?? "Action failed."); return; } setMessage(success); router.refresh(); }); };

  return <div className="space-y-4">
    {error ? <p className="rounded-xl border border-rose-500/40 bg-rose-500/10 px-3 py-2 text-sm text-rose-200">{error}</p> : null}{message ? <p className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">{message}</p> : null}
    <details className="group rounded-2xl border border-[#2d7dff]/20 bg-black/40 p-3"><summary className="flex cursor-pointer list-none items-center justify-between"><div><p className="font-medium text-white">Add catalog part</p><p className="text-xs text-zinc-500">Open only when adding new inventory</p></div><ChevronDown className="h-4 w-4 text-[#bafcfc] transition group-open:rotate-180" /></summary><div className="mt-3"><div className="grid gap-2 md:grid-cols-5"><input value={newPart.name} onChange={(e) => setNewPart({ ...newPart, name: e.target.value })} placeholder="Part name" className="rounded-xl border border-[#2d7dff]/20 bg-black px-3 py-2 text-white" /><input value={newPart.partNumber} onChange={(e) => setNewPart({ ...newPart, partNumber: e.target.value })} placeholder="Part #" className="rounded-xl border border-[#2d7dff]/20 bg-black px-3 py-2 text-white" /><input type="number" min="0" step="0.01" value={newPart.defaultCost} onChange={(e) => setNewPart({ ...newPart, defaultCost: e.target.value })} placeholder="Cost" className="rounded-xl border border-[#2d7dff]/20 bg-black px-3 py-2 text-white" /><input type="number" min="0" step="0.01" value={newPart.retailPrice} onChange={(e) => setNewPart({ ...newPart, retailPrice: e.target.value })} placeholder="Retail" className="rounded-xl border border-[#2d7dff]/20 bg-black px-3 py-2 text-white" /><input type="number" min="0" value={newPart.stock} onChange={(e) => setNewPart({ ...newPart, stock: e.target.value })} placeholder="Stock" className="rounded-xl border border-[#2d7dff]/20 bg-black px-3 py-2 text-white" /></div><button onClick={() => run(() => createPartAction({ name: newPart.name, partNumber: newPart.partNumber, defaultCost: Number(newPart.defaultCost), retailPrice: Number(newPart.retailPrice), stock: Number(newPart.stock) }), "Part added.")} disabled={pending || !newPart.name.trim() || !newPart.partNumber.trim()} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-[#2d7dff] bg-[#2d7dff]/10 px-4 py-2 text-sm text-[#d9fbff] disabled:opacity-50"><Plus className="h-4 w-4" />Add part</button></div></details>
    <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-zinc-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search parts by name or part number" className="w-full rounded-2xl border border-[#2d7dff]/20 bg-black/40 py-2.5 pl-10 pr-3 text-white" /></div>
    <details className="group rounded-2xl border border-[#2d7dff]/20 bg-black/35 p-3"><summary className="flex cursor-pointer list-none items-center justify-between"><div><p className="font-medium text-white">Parts inventory</p><p className="text-xs text-zinc-500">{filtered.length} shown • hidden until needed</p></div><ChevronDown className="h-4 w-4 text-[#bafcfc] transition group-open:rotate-180" /></summary><div className="mt-3 overflow-x-auto"><div className="min-w-[430px]"><div className="grid grid-cols-[minmax(0,1.6fr)_64px_92px_92px] gap-2 border-b border-[#2d7dff]/20 px-3 pb-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-500"><span>Name</span><span className="text-right">Qty</span><span className="text-right">Cost</span><span className="text-right">Retail</span></div><div className="mt-2 space-y-2">{filtered.map((part) => <PartRow key={part.id} part={part} pending={pending} save={(data) => run(() => updatePartAction(data), "Part updated.")} remove={() => run(() => deletePartAction(part.id), "Part deleted.")} />)}{filtered.length === 0 ? <p className="px-3 py-2 text-sm text-zinc-500">No matching parts.</p> : null}</div></div></div></details>
    <details className="group rounded-2xl border border-[#2d7dff]/20 bg-black/35 p-3"><summary className="flex cursor-pointer list-none items-center justify-between"><div><p className="font-medium text-white">Baseline fees</p><p className="text-xs text-zinc-500">{fees.length} service fee presets</p></div><ChevronDown className="h-4 w-4 text-[#bafcfc] transition group-open:rotate-180" /></summary><div className="mt-3 space-y-2">{fees.map((fee) => <FeeRow key={fee.id} fee={fee} pending={pending} save={(amount) => run(() => updateFeeAction(fee.id, amount), "Fee updated.")} />)}</div></details>
  </div>;
}

function PartRow({ part, pending, save, remove }: { part: PartsCatalogItem; pending: boolean; save: (input: Parameters<typeof updatePartAction>[0]) => void; remove: () => void }) {
  const [name, setName] = useState(part.name); const [partNumber, setPartNumber] = useState(part.partNumber); const [cost, setCost] = useState(String(part.defaultCost)); const [retail, setRetail] = useState(String(part.retailPrice)); const [stock, setStock] = useState(String(part.stock));
  return <details className="group/part rounded-xl border border-[#2d7dff]/15 bg-zinc-950/70"><summary className="relative grid cursor-pointer list-none grid-cols-[minmax(0,1.6fr)_64px_92px_92px] gap-2 px-3 py-3 text-sm"><span className="truncate pr-4 font-medium text-white">{part.name}</span><span className="text-right text-zinc-200">{part.stock}</span><span className="text-right text-zinc-300">{money(part.defaultCost)}</span><span className="text-right font-medium text-[#bafcfc]">{money(part.retailPrice)}</span><ChevronDown className="absolute left-[calc(100%-18px)] top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[#8ffafa]/60 transition group-open/part:rotate-180" /></summary><div className="border-t border-[#2d7dff]/10 p-3"><p className="mb-2 text-xs text-zinc-500">Edit details • Part #{part.partNumber}</p><div className="grid gap-2 md:grid-cols-[1.4fr_1fr_110px_110px_90px_auto_auto]"><input aria-label="Part name" value={name} onChange={(e) => setName(e.target.value)} className="rounded-lg border border-[#2d7dff]/15 bg-black px-2 py-2 text-sm text-white" /><input aria-label="Part number" value={partNumber} onChange={(e) => setPartNumber(e.target.value)} className="rounded-lg border border-[#2d7dff]/15 bg-black px-2 py-2 text-sm text-white" /><input aria-label="Cost" type="number" min="0" step="0.01" value={cost} onChange={(e) => setCost(e.target.value)} className="rounded-lg border border-[#2d7dff]/15 bg-black px-2 py-2 text-sm text-white" /><input aria-label="Retail price" type="number" min="0" step="0.01" value={retail} onChange={(e) => setRetail(e.target.value)} className="rounded-lg border border-[#2d7dff]/15 bg-black px-2 py-2 text-sm text-white" /><input aria-label="Quantity" type="number" min="0" value={stock} onChange={(e) => setStock(e.target.value)} className="rounded-lg border border-[#2d7dff]/15 bg-black px-2 py-2 text-sm text-white" /><button onClick={() => save({ id: part.id, name, partNumber, defaultCost: Number(cost), retailPrice: Number(retail), stock: Number(stock) })} disabled={pending} className="rounded-lg border border-[#2d7dff]/30 p-2 text-[#d9fbff] disabled:opacity-50" aria-label={`Save ${part.name}`}><Save className="h-4 w-4" /></button><button onClick={remove} disabled={pending} className="rounded-lg border border-rose-500/20 p-2 text-rose-300 disabled:opacity-50" aria-label={`Delete ${part.name}`}><Trash2 className="h-4 w-4" /></button></div></div></details>;
}
function FeeRow({ fee, pending, save }: { fee: FeeSetting; pending: boolean; save: (amount: number) => void }) { const [amount, setAmount] = useState(String(fee.amount)); return <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#2d7dff]/15 bg-zinc-950/70 p-3"><span className="text-sm text-white">{fee.label}</span><div className="flex items-center gap-2"><input type="number" min="0" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} className="w-28 rounded-lg border border-[#2d7dff]/15 bg-black px-2 py-2 text-sm text-white" /><button onClick={() => save(Number(amount))} disabled={pending} className="rounded-lg border border-[#2d7dff]/30 p-2 text-[#d9fbff] disabled:opacity-50"><Save className="h-4 w-4" /></button></div></div>; }
