import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { SectionCard } from "@/components/section-card";
import { StatusPill } from "@/components/status-pill";
import { getOpenWorkOrders } from "@/lib/chillbros/open-work-orders";
import { getActiveTechnicians } from "@/lib/chillbros/operations-queries";
import { JOB_STATUS_LABELS, type JobStatus } from "@/lib/chillbros/types";
import { getCurrentStaffProfile } from "@/lib/supabase/auth-server";
import { markReadyToInvoiceAction, updateWorkOrderAssignmentAction, updateWorkOrderStatusAction } from "./actions";

export const dynamic="force-dynamic";
type Props={searchParams:Promise<{tech?:string;status?:string;q?:string;sort?:string;success?:string;error?:string}>};
const selectClass="min-h-10 rounded-xl border border-[#2d7dff]/20 bg-black px-3 text-sm text-white";
const stages:JobStatus[]=["needs_scheduling","scheduled","dispatched","en_route","arrived","diagnosing","awaiting_approval","approved","parts_required","return_visit_needed","repairing","work_complete","ready_to_invoice","invoice_sent","completed","cancelled"];

export default async function WorkOrdersPage({searchParams}:Props){
 const p=await getCurrentStaffProfile(); if(!p||p.role!=="manager") redirect("/");
 const params=await searchParams; const [rows,techs]=await Promise.all([getOpenWorkOrders(),getActiveTechnicians()]);
 let filtered=rows.filter(r=>(!params.tech||r.assignedTechId===params.tech)&&(!params.status||r.status===params.status)&&(!params.q||[r.customerName,r.jobNumber,r.location,r.scope,r.assignedTechName].some(v=>String(v??"").toLowerCase().includes(params.q!.toLowerCase()))));
 if(params.sort==="schedule") filtered.sort((a,b)=>String(a.scheduledWindow??"9999").localeCompare(String(b.scheduledWindow??"9999")));
 else if(params.sort==="tech") filtered.sort((a,b)=>String(a.assignedTechName??"ZZZ").localeCompare(String(b.assignedTechName??"ZZZ")));
 else if(params.sort==="status") filtered.sort((a,b)=>a.status.localeCompare(b.status));
 const unassigned=rows.filter(r=>!r.assignedTechId).length, billing=rows.filter(r=>["ready_to_invoice","invoice_sent"].includes(r.status)).length, returns=rows.filter(r=>r.status==="return_visit_needed").length;
 return <AppShell title="Open Work Orders" description="Every active service call in one place. Reassign it, move the workflow, send it to billing, or cancel it without chasing tabs."><div className="space-y-4">
  {(params.success||params.error)?<div className={`rounded-xl border p-3 text-sm ${params.error?"border-red-400/30 bg-red-400/5 text-red-100":"border-emerald-400/30 bg-emerald-400/5 text-emerald-100"}`}>{params.error||params.success}</div>:null}
  <div className="grid grid-cols-2 gap-2 md:grid-cols-4"><div className="rounded-2xl border border-[#2d7dff]/20 bg-black/45 p-4 text-center"><p className="text-2xl font-semibold text-white">{rows.length}</p><p className="text-[10px] uppercase tracking-[.14em] text-zinc-500">Open calls</p></div><div className="rounded-2xl border border-amber-400/20 bg-black/45 p-4 text-center"><p className="text-2xl font-semibold text-white">{unassigned}</p><p className="text-[10px] uppercase tracking-[.14em] text-zinc-500">Unassigned</p></div><div className="rounded-2xl border border-[#2d7dff]/20 bg-black/45 p-4 text-center"><p className="text-2xl font-semibold text-white">{returns}</p><p className="text-[10px] uppercase tracking-[.14em] text-zinc-500">Return visits</p></div><div className="rounded-2xl border border-emerald-400/20 bg-black/45 p-4 text-center"><p className="text-2xl font-semibold text-white">{billing}</p><p className="text-[10px] uppercase tracking-[.14em] text-zinc-500">Billing queue</p></div></div>
  <SectionCard eyebrow="Control board" title="Find the call you need"><form className="grid gap-2 md:grid-cols-5"><input name="q" defaultValue={params.q||""} placeholder="Customer, location, tech, scope..." className={selectClass}/><select name="tech" defaultValue={params.tech||""} className={selectClass}><option value="">All technicians</option>{techs.map(t=><option key={t.id} value={t.id}>{t.fullName}</option>)}</select><select name="status" defaultValue={params.status||""} className={selectClass}><option value="">All stages</option>{stages.map(s=><option key={s} value={s}>{JOB_STATUS_LABELS[s]}</option>)}</select><select name="sort" defaultValue={params.sort||"newest"} className={selectClass}><option value="newest">Newest first</option><option value="schedule">Schedule time</option><option value="tech">Technician</option><option value="status">Workflow stage</option></select><button className="rounded-xl border border-[#8ffafa]/30 bg-[#2d7dff]/15 px-4 py-2 text-sm font-semibold text-[#d9fbff]">Apply</button></form></SectionCard>
  <div className="space-y-3">{filtered.length?filtered.map(r=><SectionCard key={r.id} eyebrow={r.jobNumber||"Work order"} title={r.customerName} description={[r.scheduledWindow,r.location].filter(Boolean).join(" · ")||"No schedule/location entered"}><div className="space-y-3"><div className="flex flex-wrap items-center gap-2"><StatusPill>{JOB_STATUS_LABELS[r.status]}</StatusPill><StatusPill>{r.assignedTechName||"Unassigned"}</StatusPill>{r.invoiceNumber?<StatusPill>{`${r.invoiceNumber} · ${r.invoiceStatus}`}</StatusPill>:null}</div>{r.scope?<p className="text-sm leading-6 text-zinc-300">{r.scope}</p>:null}<div className="grid gap-2 lg:grid-cols-3">
    <form action={updateWorkOrderAssignmentAction} className="flex gap-2"><input type="hidden" name="jobId" value={r.id}/><select name="technicianId" defaultValue={r.assignedTechId||""} className={`${selectClass} min-w-0 flex-1`}><option value="">Unassigned</option>{techs.map(t=><option key={t.id} value={t.id}>{t.fullName}</option>)}</select><button className="rounded-xl border border-[#2d7dff]/30 px-3 text-xs text-white">Assign</button></form>
    <form action={updateWorkOrderStatusAction} className="flex gap-2"><input type="hidden" name="jobId" value={r.id}/><select name="status" defaultValue={r.status} className={`${selectClass} min-w-0 flex-1`}>{stages.map(s=><option key={s} value={s}>{JOB_STATUS_LABELS[s]}</option>)}</select><button className="rounded-xl border border-[#2d7dff]/30 px-3 text-xs text-white">Update</button></form>
    <div className="grid grid-cols-3 gap-2"><Link href={`/schedule?job=${r.id}`} className="rounded-xl border border-[#2d7dff]/25 px-2 py-2 text-center text-xs text-white">Schedule</Link><form action={markReadyToInvoiceAction}><input type="hidden" name="jobId" value={r.id}/><button className="h-full w-full rounded-xl border border-emerald-400/25 px-2 py-2 text-xs text-emerald-100">To Invoice</button></form><Link href={`/jobs/${r.id}`} className="rounded-xl border border-[#2d7dff]/25 px-2 py-2 text-center text-xs text-white">Open Job</Link></div>
   </div><p className="text-[11px] text-zinc-500">Manual workflow changes are audit-logged. Cancellation is available in the stage selector.</p></div></SectionCard>):<SectionCard title="No matching open work orders"><p className="text-sm text-zinc-500">Nothing matches these filters.</p></SectionCard>}</div>
 </div></AppShell>;
}
