import Link from "next/link";
import { redirect } from "next/navigation";
import { ExternalLink, FileDown, FileText, Plus, ReceiptText, Search } from "lucide-react";

import { AppShell } from "@/components/app-shell";
import { InvoiceAdminControls } from "@/components/invoice-admin-controls";
import { SectionCard } from "@/components/section-card";
import { StatusPill } from "@/components/status-pill";
import { getInvoiceCenterData, type InvoiceCenterRow } from "@/lib/chillbros/billing-queries";
import { getCurrentStaffProfile } from "@/lib/supabase/auth-server";
import { PAYMENT_TERMS_LABELS } from "@/lib/chillbros/types";

export const dynamic = "force-dynamic";
type Props = { searchParams: Promise<{ q?: string; status?: string; focus?: string; created?: string }> };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const FILTERS = [["all","All"],["draft","Draft"],["awaiting","Awaiting approval"],["approved_unpaid","Approved / unpaid"],["overdue","Overdue"],["paid","Paid"],["void","Void"]] as const;
function date(value: string | null) { return value ? new Date(value).toLocaleDateString("en-US", { timeZone: "America/Chicago", month: "short", day: "numeric", year: "numeric" }) : "—"; }
function time(value: string | null) { return value ? new Date(value).toLocaleString("en-US", { timeZone: "America/Chicago", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "—"; }
function visible(row: InvoiceCenterRow, filter: string, query: string) { const statusMatch = filter === "all" || (filter === "draft" && row.status === "draft") || (filter === "awaiting" && row.status === "awaiting_approval") || (filter === "approved_unpaid" && row.status === "approved" && row.paymentStatus !== "paid") || (filter === "overdue" && row.daysOverdue > 0) || (filter === "paid" && row.paymentStatus === "paid") || (filter === "void" && row.status === "void"); if (!statusMatch) return false; if (!query) return true; return [row.invoiceNumber,row.customerName,row.customerEmail,row.customerPhone,row.jobLocation,row.jobScope,row.technicianName,...row.equipment].filter(Boolean).join(" ").toLowerCase().includes(query); }

export default async function InvoicesPage({ searchParams }: Props) {
  const profile = await getCurrentStaffProfile(); if (!profile || !["manager","office"].includes(profile.role)) redirect("/");
  const params = await searchParams; const filter = FILTERS.some(([value]) => value === params.status) ? String(params.status) : "all"; const query = String(params.q || "").trim().toLowerCase();
  const { rows, metrics } = await getInvoiceCenterData(); const focused = params.focus ? rows.find((row) => row.id === params.focus) ?? null : null; const filtered = focused ? [focused] : rows.filter((row) => visible(row, filter, query)); const canManage = profile.role === "manager";
  const renderCard = (row: InvoiceCenterRow, simple = false) => { const paid = row.paymentStatus === "paid"; const approved = row.status === "approved"; const tone = paid ? "emerald" : row.daysOverdue > 0 ? "amber" : approved ? "emerald" : row.status === "void" ? undefined : "amber"; return <article key={row.id} className={`rounded-2xl border ${simple ? "border-[#8ffafa]/40 bg-[#06111b]/95 shadow-[0_0_30px_rgba(45,125,255,0.14)]" : "border-[#2d7dff]/20 bg-zinc-950/75"} p-4`}>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.16em] text-zinc-500">{row.invoiceNumber}</p><h3 className="mt-1 text-lg font-semibold text-white">{row.customerName}</h3>{simple ? <p className="mt-1 text-sm text-zinc-400">{row.customerEmail ?? "No email saved"} · {row.customerPhone ?? "No phone saved"}</p> : <p className="mt-1 text-xs text-zinc-500">Updated {time(row.updatedAt)}</p>}</div><div className="text-right"><p className="text-2xl font-semibold text-[#bafcfc]">{money.format(row.total)}</p><div className="mt-2 flex flex-wrap justify-end gap-2"><StatusPill tone={tone}>{paid ? "Paid" : row.status.replace(/_/g," ")}</StatusPill></div></div></div>
    {simple ? <><div className="mt-4 rounded-2xl border border-[#2d7dff]/20 bg-black/35 p-3"><p className="text-xs uppercase tracking-[0.16em] text-[#8ffafa]">Send to customer</p><p className="mt-1 text-sm text-zinc-400">Preview the customer document, then send it by email or text. The saved email and mobile number are used automatically.</p></div><div className="mt-3 flex flex-wrap gap-2"><Link href={`/portal/${row.portalToken}/document`} target="_blank" className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-[#8ffafa]/45 bg-[#2d7dff]/15 px-4 py-3 font-semibold text-white"><FileText className="h-4 w-4" />Preview document</Link><Link href={`/portal/${row.portalToken}`} target="_blank" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#2d7dff]/25 px-4 py-3 text-sm text-[#d9fbff]"><ExternalLink className="h-4 w-4" />Customer view</Link></div><div className="mt-4"><InvoiceAdminControls invoiceId={row.id} status={row.status} paymentStatus={row.paymentStatus} taxRate={row.taxRate} paymentTerms={row.paymentTerms} dueAt={row.dueAt} taxExempt={row.customerTaxExempt} taxExemptNote={row.customerTaxExemptNote} hasApprovedArchive={row.hasApprovedArchive} hasPaidArchive={row.hasPaidArchive} canManage={canManage} /></div></> : <>
      <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl border border-[#2d7dff]/10 bg-black/35 p-3"><p className="text-xs text-zinc-500">Billing</p><p className="mt-1 text-sm text-white">{PAYMENT_TERMS_LABELS[row.paymentTerms]}</p><p className="mt-1 text-xs text-zinc-400">Due {date(row.dueAt)} · Aging {row.agingBucket}</p></div><div className="rounded-xl border border-[#2d7dff]/10 bg-black/35 p-3"><p className="text-xs text-zinc-500">Customer</p><p className="mt-1 text-sm text-white">{row.customerEmail ?? "No email"}</p><p className="mt-1 text-xs text-zinc-400">{row.customerPhone ?? "No phone"}</p></div><div className="rounded-xl border border-[#2d7dff]/10 bg-black/35 p-3"><p className="text-xs text-zinc-500">Service</p><p className="mt-1 text-sm text-white">{row.jobLocation ?? "Direct invoice"}</p>{row.jobScope ? <p className="mt-1 line-clamp-2 text-xs text-zinc-500">{row.jobScope}</p> : null}</div><div className="rounded-xl border border-[#2d7dff]/10 bg-black/35 p-3"><p className="text-xs text-zinc-500">Delivery</p><p className="mt-1 text-sm text-white">{row.latestDelivery ? `${row.latestDelivery.channel} · ${row.latestDelivery.status}` : "Not sent yet"}</p></div></div>
      <div className="mt-3 flex flex-wrap gap-2">{row.status !== "void" ? <Link href={`/portal/${row.portalToken}/document`} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-[#2d7dff]/25 px-3 py-2 text-xs text-[#d9fbff]"><FileText className="h-3.5 w-3.5" />Document</Link> : null}{row.status !== "void" ? <Link href={`/portal/${row.portalToken}`} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-[#2d7dff]/25 px-3 py-2 text-xs text-[#d9fbff]"><ExternalLink className="h-3.5 w-3.5" />Customer view</Link> : null}{row.hasApprovedArchive ? <Link href={`/api/portal/${row.portalToken}/pdf?stage=approved`} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-[#2d7dff]/25 px-3 py-2 text-xs text-[#d9fbff]"><FileDown className="h-3.5 w-3.5" />PDF</Link> : null}{row.receiptNumber ? <Link href={`/portal/${row.portalToken}/receipt`} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-emerald-400/25 px-3 py-2 text-xs text-emerald-100"><ReceiptText className="h-3.5 w-3.5" />Receipt</Link> : null}</div>
      <div className="mt-4 border-t border-[#2d7dff]/10 pt-4"><InvoiceAdminControls invoiceId={row.id} status={row.status} paymentStatus={row.paymentStatus} taxRate={row.taxRate} paymentTerms={row.paymentTerms} dueAt={row.dueAt} taxExempt={row.customerTaxExempt} taxExemptNote={row.customerTaxExemptNote} hasApprovedArchive={row.hasApprovedArchive} hasPaidArchive={row.hasPaidArchive} canManage={canManage} /></div></>}
  </article>; };

  return <AppShell title="Invoice Center" description={focused ? "Invoice ready. Preview it and send it to the customer." : "Create, send, track, and collect invoices without digging through jobs."}>
    <div className="space-y-5">
      {focused ? <><section className="rounded-3xl border border-emerald-400/30 bg-emerald-500/[0.06] p-4 sm:p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-200">Invoice created</p><h2 className="mt-1 text-2xl font-semibold text-white">Ready to send</h2><p className="mt-1 text-sm text-zinc-400">No hunting through the invoice list. Review this document and send it now.</p></section>{renderCard(focused,true)}<div className="flex flex-wrap gap-2"><Link href="/invoices/new?type=invoice" className="inline-flex items-center gap-2 rounded-xl border border-[#2d7dff]/25 px-4 py-3 text-sm text-[#d9fbff]"><Plus className="h-4 w-4" />New invoice</Link><Link href="/invoices" className="rounded-xl border border-[#2d7dff]/25 px-4 py-3 text-sm text-zinc-300">All invoices</Link></div></> : <>
        <div className="grid gap-3 sm:grid-cols-2"><Link href="/invoices/new?type=invoice" className="rounded-2xl border border-[#8ffafa]/45 bg-[#2d7dff]/15 p-4 text-center font-semibold text-white">+ New Invoice</Link><Link href="/invoices/new?type=quote" className="rounded-2xl border border-[#2d7dff]/25 p-4 text-center font-semibold text-[#d9fbff]">+ New Quote</Link></div>
        <SectionCard eyebrow="Receivables" title="Billing dashboard" description="The numbers you need without making invoice sending compete with accounting controls."><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Outstanding",money.format(metrics.outstandingValue)],["Overdue",money.format(metrics.overdueValue)],["Collected month",money.format(metrics.collectedThisMonth)],["Awaiting",String(metrics.pendingApproval)]].map(([l,v]) => <div key={l} className="rounded-2xl border border-[#2d7dff]/20 bg-black/40 p-3"><p className="text-xs text-zinc-500">{l}</p><p className="mt-2 text-xl font-semibold text-white">{v}</p></div>)}</div></SectionCard>
        <SectionCard eyebrow="Find" title="Invoices" description="Search or filter, then open the document you need."><form className="flex flex-col gap-2 sm:flex-row" action="/invoices" method="get"><input type="hidden" name="status" value={filter}/><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-zinc-500"/><input name="q" defaultValue={params.q ?? ""} placeholder="Customer or invoice number" className="w-full rounded-xl border border-[#2d7dff]/20 bg-zinc-950 py-2.5 pl-10 pr-3 text-white"/></label><button className="rounded-xl border border-[#2d7dff]/30 px-4 py-2.5 text-sm text-[#d9fbff]">Search</button></form><div className="mt-3 flex flex-wrap gap-2">{FILTERS.map(([value,label]) => <Link key={value} href={`/invoices?status=${value}`} className={`rounded-full border px-3 py-1.5 text-xs ${filter === value ? "border-[#8ffafa]/60 bg-[#2d7dff]/20 text-white" : "border-[#2d7dff]/20 text-zinc-400"}`}>{label}</Link>)}</div></SectionCard>
        <SectionCard eyebrow="Ledger" title={`${filtered.length} document${filtered.length === 1 ? "" : "s"}`} description="Customer, total, status, delivery, and the actions that matter.">{filtered.length ? <div className="space-y-4">{filtered.map((row) => renderCard(row))}</div> : <p className="text-sm text-zinc-400">No invoices match this view.</p>}</SectionCard>
      </>}
    </div>
  </AppShell>;
}
