create table if not exists public.chillbros_login_attempts (
  id bigint generated by default as identity primary key,
  identity_hash text not null,
  ip_hash text not null,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists chillbros_login_attempts_identity_time_idx
  on public.chillbros_login_attempts (identity_hash, attempted_at desc);
create index if not exists chillbros_login_attempts_ip_time_idx
  on public.chillbros_login_attempts (ip_hash, attempted_at desc);
create index if not exists chillbros_login_attempts_time_idx
  on public.chillbros_login_attempts (attempted_at desc);

alter table public.chillbros_login_attempts enable row level security;
revoke all on table public.chillbros_login_attempts from anon, authenticated;
grant select, insert, update, delete on table public.chillbros_login_attempts to service_role;

do $$ begin
  if exists (select 1 from pg_class where relname = 'chillbros_login_attempts_id_seq') then
    grant usage, select on sequence public.chillbros_login_attempts_id_seq to service_role;
  end if;
end $$;
